# Generated by Django 3.0.2 on 2020-01-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouyeel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouyeel',
            name='smallFrontPicUrl',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='前置图标url地址'),
        ),
        migrations.AlterField(
            model_name='ouyeel',
            name='specComment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='规格简要说明'),
        ),
    ]
