# Generated by Django 3.0.2 on 2020-01-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouyeel', '0002_auto_20200123_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouyeel',
            name='specComment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='规格简要说明'),
        ),
    ]
