# Generated by Django 3.0.2 on 2020-01-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouyeel', '0003_auto_20200124_0019'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ouyeel',
            index=models.Index(fields=['productCode'], name='Ouyeel_product_346cdb_idx'),
        ),
    ]
