# Generated by Django 3.0.2 on 2020-01-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouyeel', '0004_auto_20200124_1225'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ouyeel',
            name='Ouyeel_createD_84e7d1_idx',
        ),
        migrations.AddIndex(
            model_name='ouyeel',
            index=models.Index(fields=['providerName'], name='Ouyeel_provide_ae51a4_idx'),
        ),
    ]
